name: Build & Deploy TorizonCore
on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy TorizonCore
    container:
      image: torizonextras/torizon-dev:dev
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: storage/
          key: tcb

      - name: Get Host Absolute Workspace Path
        run: |
          echo "${{ github.workspace }}" >> abs-path
          cat abs-path

      - name: Decode Credentials
        env:
          PLATFORM_CREDENTIALS: ${{ secrets.PLATFORM_CREDENTIALS }}
        run: |
          echo $PLATFORM_CREDENTIALS | base64 -d > credentials.zip

      - name: Build TorizonCore Image
        shell: xonsh {0}
        run: |
          xonsh ./.vscode/tasks.xsh run tcb-setup
          xonsh ./.vscode/tasks.xsh run tcb-build
